use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct Constants {
    protocol_version: u8,
    socket_path_limit: usize,
    max_message_size: usize,
}

fn main() {
    // 1. Re-run if config changes
    println!("cargo:rerun-if-changed=../../config/constants.toml");

    // 2. Read and Parse TOML (Strict SSoT)
    let config_path = Path::new("../../config/constants.toml");
    let content = fs::read_to_string(config_path).expect("Failed to read config/constants.toml");
    let constants: Constants =
        toml::from_str(&content).expect("Failed to parse config/constants.toml - Schema Mismatch!");

    // 3. Generate Rust Constants
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("constants.rs");

    let rust_code = format!(
        "// Auto-generated by build.rs. DO NOT EDIT.\n\
         pub const PROTOCOL_VERSION: u8 = {protocol_version};\n\
         pub const SOCKET_PATH_LIMIT: usize = {socket_path_limit};\n\
         pub const MAX_MESSAGE_SIZE: usize = {max_message_size};\n",
        protocol_version = constants.protocol_version,
        socket_path_limit = constants.socket_path_limit,
        max_message_size = constants.max_message_size,
    );

    fs::write(&dest_path, rust_code).expect("Failed to write constants.rs");
}
