use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    // 1. Re-run if config changes
    println!("cargo:rerun-if-changed=config/constants.toml");
    println!("cargo:rerun-if-changed=assets/");

    // RFC-0018: UV Embedding (only when feature enabled)
    #[cfg(feature = "embedded_uv")]
    {
        embed_uv_binary();
    }

    // 1b. Capture Git Hash
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output();
    let mut git_hash = match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    };

    // Check for uncommitted changes
    let is_dirty = Command::new("git")
        .args(["status", "--porcelain"])
        .output()
        .map(|o| !o.stdout.is_empty())
        .unwrap_or(false);

    if is_dirty {
        git_hash.push_str("-dirty");
    }

    // 2. Read TOML
    let config_path = Path::new("config/constants.toml");
    let content = fs::read_to_string(config_path).expect("Failed to read config/constants.toml");

    // 3. Extract strictly compile-time constants
    let protocol_version = extract_u64(&content, "protocol_version");
    let socket_limit = extract_u64(&content, "socket_path_limit");
    let max_message_size = extract_u64(&content, "max_message_size");
    let socket_startup_timeout = extract_u64(&content, "socket_startup_timeout");
    let graceful_shutdown_timeout = extract_u64(&content, "graceful_shutdown_timeout");
    let default_port = extract_u64(&content, "default_port");

    // Security profiles (for Python parity) - Hierarchical Matrix
    // Level 0: Global Base
    let security_base_prefixes = extract_str(&content, "security_base_trusted_prefixes");
    let security_base_envs = extract_str(&content, "security_base_env_whitelist");

    // Level 1: macOS Base
    let security_macos_base_prefixes =
        extract_str(&content, "security_macos_base_trusted_prefixes");
    let security_macos_base_envs = extract_str(&content, "security_macos_base_env_whitelist");

    // Level 1: Linux Base
    let security_linux_base_prefixes =
        extract_str(&content, "security_linux_base_trusted_prefixes");
    let security_linux_base_envs = extract_str(&content, "security_linux_base_env_whitelist");

    // Level 2: macOS Environments
    let security_macos_dev_prefixes = extract_str(&content, "security_macos_dev_trusted_prefixes");
    let security_macos_dev_envs = extract_str(&content, "security_macos_dev_env_whitelist");
    let security_macos_ci_prefixes = extract_str(&content, "security_macos_ci_trusted_prefixes");
    let security_macos_ci_envs = extract_str(&content, "security_macos_ci_env_whitelist");
    let security_macos_prod_prefixes =
        extract_str(&content, "security_macos_prod_trusted_prefixes");
    let security_macos_prod_envs = extract_str(&content, "security_macos_prod_env_whitelist");

    // Level 2: Linux Environments
    let security_linux_dev_prefixes = extract_str(&content, "security_linux_dev_trusted_prefixes");
    let security_linux_dev_envs = extract_str(&content, "security_linux_dev_env_whitelist");
    let security_linux_ci_prefixes = extract_str(&content, "security_linux_ci_trusted_prefixes");
    let security_linux_ci_envs = extract_str(&content, "security_linux_ci_env_whitelist");
    let security_linux_prod_prefixes =
        extract_str(&content, "security_linux_prod_trusted_prefixes");
    let security_linux_prod_envs = extract_str(&content, "security_linux_prod_env_whitelist");

    // 4. Generate Rust Constants
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("constants.rs");

    let rust_code = format!(
        "// Auto-generated by build.rs. DO NOT EDIT.\n\
         pub const PROTOCOL_VERSION: u8 = {};\n\
         pub const SOCKET_PATH_LIMIT: usize = {};\n\
         pub const MAX_MESSAGE_SIZE: usize = {};\n\
         pub const SOCKET_STARTUP_TIMEOUT: u64 = {};\n\
         pub const GRACEFUL_SHUTDOWN_TIMEOUT: u64 = {};\n\
         pub const DEFAULT_PORT: u16 = {};\n",
        protocol_version,
        socket_limit,
        max_message_size,
        socket_startup_timeout,
        graceful_shutdown_timeout,
        default_port
    );
    fs::write(&dest_path, rust_code).unwrap();

    // Extract Path Matrix
    // Level 0: Templates
    let path_socket_dir_name = extract_str(&content, "path_socket_dir_name");
    let path_log_dir_relative = extract_str(&content, "path_log_dir_relative");

    // Level 1: macOS Base
    let path_macos_base_socket_parent = extract_str(&content, "path_macos_base_socket_parent");
    let path_macos_base_log_parent = extract_str(&content, "path_macos_base_log_parent");

    // Level 1: Linux Base
    let path_linux_base_socket_parent = extract_str(&content, "path_linux_base_socket_parent");
    let path_linux_base_log_parent = extract_str(&content, "path_linux_base_log_parent");

    // Level 2: Environment Overlays
    let path_macos_ci_socket_parent = extract_str(&content, "path_macos_ci_socket_parent");
    let path_linux_ci_socket_parent = extract_str(&content, "path_linux_ci_socket_parent");
    let path_linux_fd_dir = extract_str(&content, "path_linux_fd_dir");
    let path_macos_fd_dir = extract_str(&content, "path_macos_fd_dir");

    // 5. Generate Python Constants
    let py_path = Path::new("velo_zygote/constants.py");
    // Indent for readability in Python file

    let python_constants = format!(
        r#"# Auto-generated by build.rs. DO NOT EDIT.
import sys

BUILD_SCM_HASH = "{build_hash}"
PROTOCOL_VERSION = {}
SOCKET_PATH_LIMIT = {}
MAX_MESSAGE_SIZE = {}
SOCKET_STARTUP_TIMEOUT = {}
GRACEFUL_SHUTDOWN_TIMEOUT = {}
DEFAULT_PORT = {}

# Valid Environment Variables
# VELO_ENV: dev, ci, prod
# VELO_SOCKET_DIR: Override socket directory
# VELO_ZYGOTE_LOG: Override log file path

# Level 0: Global Base (Universal)
SECURITY_BASE_TRUSTED_PREFIXES = "{}"
SECURITY_BASE_ENV_WHITELIST = "{}"
PATH_SOCKET_DIR_NAME = "{}"
PATH_LOG_DIR_RELATIVE = "{}"

# Level 1: macOS specific
if sys.platform == "darwin":
    SECURITY_MACOS_BASE_TRUSTED_PREFIXES = "{}"
    SECURITY_MACOS_BASE_ENV_WHITELIST = "{}"
    # Level 2: macOS Environment Overlays
    SECURITY_MACOS_DEV_TRUSTED_PREFIXES = "{}"
    SECURITY_MACOS_DEV_ENV_WHITELIST = "{}"
    SECURITY_MACOS_CI_TRUSTED_PREFIXES = "{}"
    SECURITY_MACOS_CI_ENV_WHITELIST = "{}"
    SECURITY_MACOS_PROD_TRUSTED_PREFIXES = "{}"
    SECURITY_MACOS_PROD_ENV_WHITELIST = "{}"
    # Paths
    PATH_MACOS_BASE_SOCKET_PARENT = "{}"
    PATH_MACOS_BASE_LOG_PARENT = "{}"
    PATH_MACOS_CI_SOCKET_PARENT = "{}"
    PATH_MACOS_FD_DIR = "{}"

# Level 1: Linux specific
if sys.platform == "linux":
    SECURITY_LINUX_BASE_TRUSTED_PREFIXES = "{}"
    SECURITY_LINUX_BASE_ENV_WHITELIST = "{}"
    # Level 2: Linux Environment Overlays
    SECURITY_LINUX_DEV_TRUSTED_PREFIXES = "{}"
    SECURITY_LINUX_DEV_ENV_WHITELIST = "{}"
    SECURITY_LINUX_CI_TRUSTED_PREFIXES = "{}"
    SECURITY_LINUX_CI_ENV_WHITELIST = "{}"
    SECURITY_LINUX_PROD_TRUSTED_PREFIXES = "{}"
    SECURITY_LINUX_PROD_ENV_WHITELIST = "{}"
    # Paths
    PATH_LINUX_BASE_SOCKET_PARENT = "{}"
    PATH_LINUX_BASE_LOG_PARENT = "{}"
    PATH_LINUX_CI_SOCKET_PARENT = "{}"
    PATH_LINUX_FD_DIR = "{}"

# Security (Phase 10.1)
DEFAULT_BLOCKED_PATHS = [
    "/etc", "/var", "/usr", "/bin", "/sbin",
    "/System", "/Library", "/private/etc",
    "/root", "/home",
]
"#,
        protocol_version,
        socket_limit,
        max_message_size,
        socket_startup_timeout,
        graceful_shutdown_timeout,
        default_port,
        security_base_prefixes,
        security_base_envs,
        path_socket_dir_name,
        path_log_dir_relative,
        // macOS Vars
        security_macos_base_prefixes,
        security_macos_base_envs,
        security_macos_dev_prefixes,
        security_macos_dev_envs,
        security_macos_ci_prefixes,
        security_macos_ci_envs,
        security_macos_prod_prefixes,
        security_macos_prod_envs,
        path_macos_base_socket_parent,
        path_macos_base_log_parent,
        path_macos_ci_socket_parent,
        path_macos_fd_dir,
        // Linux Vars
        security_linux_base_prefixes,
        security_linux_base_envs,
        security_linux_dev_prefixes,
        security_linux_dev_envs,
        security_linux_ci_prefixes,
        security_linux_ci_envs,
        security_linux_prod_prefixes,
        security_linux_prod_envs,
        path_linux_base_socket_parent,
        path_linux_base_log_parent,
        path_linux_ci_socket_parent,
        path_linux_fd_dir,
        build_hash = git_hash
    );
    fs::write(py_path, python_constants).unwrap();
}

fn extract_str(toml: &str, key: &str) -> String {
    for line in toml.lines() {
        let line = line.trim();
        if !line.starts_with(key) {
            continue;
        }

        if let Some(val_str) = line.split('=').nth(1) {
            return val_str.trim().trim_matches('"').to_string();
        }
    }
    "".to_string()
}

fn extract_u64(toml: &str, key: &str) -> u64 {
    for line in toml.lines() {
        let line = line.trim();
        if !line.starts_with(key) {
            continue;
        }

        if let Some(val_str) = line.split('=').nth(1) {
            return val_str
                .trim()
                .parse()
                .unwrap_or_else(|_| panic!("Invalid number for key {}", key));
        }
    }
    panic!("Key {} not found", key);
}

/// RFC-0018: Download and prepare uv binary for embedding
#[cfg(feature = "embedded_uv")]
fn embed_uv_binary() {
    use std::io::{Read, Write};

    // UV version to embed (update periodically)
    const UV_VERSION: &str = "0.9.24";

    // Platform-specific download URLs
    // Supports: macOS (arm64, x86_64), Linux (x86_64, aarch64)
    let (url, asset_name) = match (std::env::consts::OS, std::env::consts::ARCH) {
        ("macos", "aarch64") => (
            format!(
                "https://github.com/astral-sh/uv/releases/download/{}/uv-aarch64-apple-darwin.tar.gz",
                UV_VERSION
            ),
            "uv-aarch64-apple-darwin",
        ),
        ("macos", "x86_64") => (
            format!(
                "https://github.com/astral-sh/uv/releases/download/{}/uv-x86_64-apple-darwin.tar.gz",
                UV_VERSION
            ),
            "uv-x86_64-apple-darwin",
        ),
        ("linux", "x86_64") => (
            format!(
                "https://github.com/astral-sh/uv/releases/download/{}/uv-x86_64-unknown-linux-musl.tar.gz",
                UV_VERSION
            ),
            "uv-x86_64-unknown-linux-musl",
        ),
        ("linux", "aarch64") => (
            format!(
                "https://github.com/astral-sh/uv/releases/download/{}/uv-aarch64-unknown-linux-musl.tar.gz",
                UV_VERSION
            ),
            "uv-aarch64-unknown-linux-musl",
        ),
        (os, arch) => {
            println!(
                "cargo:warning=Unsupported platform for uv embedding: {}-{}",
                os, arch
            );
            return;
        }
    };

    let assets_dir = Path::new("assets");
    // Store final binary as asset_name (uv-platform), but extracted dir has same name
    // So we rename to "uv.{platform}" to avoid conflict
    let final_binary_name = format!("uv.{}", asset_name.replace("uv-", ""));
    let asset_path = assets_dir.join(&final_binary_name);
    let hash_path = assets_dir.join(format!("{}.blake3", final_binary_name));

    // Create assets directory
    fs::create_dir_all(assets_dir).expect("Failed to create assets directory");

    // Skip download if asset already exists and hash is present
    if asset_path.exists() && hash_path.exists() {
        println!(
            "cargo:warning=Using cached uv binary: {}",
            asset_path.display()
        );
        return;
    }

    println!(
        "cargo:warning=Downloading uv {} for {}...",
        UV_VERSION, asset_name
    );

    // Download using curl (available on macOS/Linux)
    let tar_gz_path = assets_dir.join(format!("{}.tar.gz", asset_name));
    let status = Command::new("curl")
        .args(["-L", "-o", tar_gz_path.to_str().unwrap(), &url])
        .status()
        .expect("Failed to execute curl");

    if !status.success() {
        panic!("Failed to download uv binary from {}", url);
    }

    // Extract the binary
    let status = Command::new("tar")
        .args([
            "-xzf",
            tar_gz_path.to_str().unwrap(),
            "-C",
            assets_dir.to_str().unwrap(),
        ])
        .status()
        .expect("Failed to execute tar");

    if !status.success() {
        panic!("Failed to extract uv binary");
    }

    // Find the extracted uv binary (it's in a subdirectory with same name)
    let extracted_dir = assets_dir.join(asset_name);
    let extracted_binary = extracted_dir.join("uv");

    // Move uv binary to assets root (asset_name without extension)
    if extracted_binary.exists() && extracted_binary.is_file() {
        fs::copy(&extracted_binary, &asset_path).expect("Failed to copy uv binary");
        // Set executable permissions
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&asset_path, fs::Permissions::from_mode(0o755))
                .expect("Failed to set permissions");
        }
        // Cleanup extracted directory
        let _ = fs::remove_dir_all(&extracted_dir);
    } else {
        panic!(
            "uv binary not found at expected path: {}",
            extracted_binary.display()
        );
    }

    // Cleanup tar.gz
    let _ = fs::remove_file(&tar_gz_path);

    // Compute BLAKE3 hash
    let mut file = fs::File::open(&asset_path).expect("Failed to open uv binary");
    let mut contents = Vec::new();
    file.read_to_end(&mut contents)
        .expect("Failed to read uv binary");

    let hash = blake3::hash(&contents);
    let hash_hex = hash.to_hex().to_string();

    // Write hash to file
    let mut hash_file = fs::File::create(&hash_path).expect("Failed to create hash file");
    hash_file
        .write_all(hash_hex.as_bytes())
        .expect("Failed to write hash");

    // Generate Rust constant for the hash
    let out_dir = env::var("OUT_DIR").unwrap();
    let uv_hash_path = Path::new(&out_dir).join("uv_hash.rs");
    let hash_code = format!(
        "// Auto-generated by build.rs for uv {}\n\
         pub const UV_BLAKE3_HASH: &str = \"{}\";\n\
         pub const UV_VERSION: &str = \"{}\";\n",
        UV_VERSION, hash_hex, UV_VERSION
    );
    fs::write(&uv_hash_path, hash_code).expect("Failed to write uv_hash.rs");

    println!(
        "cargo:warning=uv {} embedded, BLAKE3: {}...{}",
        UV_VERSION,
        &hash_hex[..8],
        &hash_hex[hash_hex.len() - 8..]
    );
}
