use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // 1. Re-run if config changes
    println!("cargo:rerun-if-changed=config/constants.toml");

    // 2. Read TOML
    let config_path = Path::new("config/constants.toml");
    let content = fs::read_to_string(config_path).expect("Failed to read config/constants.toml");

    // 3. Extract strictly compile-time constants
    let protocol_version = extract_u64(&content, "protocol_version");
    let socket_limit = extract_u64(&content, "socket_path_limit");
    let max_message_size = extract_u64(&content, "max_message_size");

    // 4. Generate Rust Constants
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("constants.rs");

    let rust_code = format!(
        "// Auto-generated by build.rs. DO NOT EDIT.\n\
         pub const PROTOCOL_VERSION: u8 = {};\n\
         pub const SOCKET_PATH_LIMIT: usize = {};\n\
         pub const MAX_MESSAGE_SIZE: usize = {};\n",
        protocol_version, socket_limit, max_message_size
    );
    fs::write(&dest_path, rust_code).unwrap();

    // 5. Generate Python Constants
    let py_path = Path::new("velo_zygote/constants.py");
    let python_constants = format!(
        "# Auto-generated by build.rs. DO NOT EDIT.\n\
         PROTOCOL_VERSION = {}\n\
         SOCKET_PATH_LIMIT = {}\n\
         MAX_MESSAGE_SIZE = {}\n",
        protocol_version, socket_limit, max_message_size
    );
    fs::write(py_path, python_constants).unwrap();
}

fn extract_u64(toml: &str, key: &str) -> u64 {
    for line in toml.lines() {
        let line = line.trim();
        if !line.starts_with(key) {
            continue;
        }

        if let Some(val_str) = line.split('=').nth(1) {
            return val_str
                .trim()
                .parse()
                .unwrap_or_else(|_| panic!("Invalid number for key {}", key));
        }
    }
    panic!("Key {} not found", key);
}
