[meta]
category = "ml"
description = "NumPy: The fundamental package for scientific computing with Python"

[test]
entry_point = "hello.py"
expected_output = "NumPy initialized: .*\\.\\s+Version: .*\\d+\\.\\d+\\.\\d+.*"
timeout = 30
