use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

#[allow(dead_code)]
#[derive(Deserialize)]
struct Constants {
    // Core
    protocol_version: u8,
    python_version: String,
    socket_path_limit: usize,
    max_message_size: usize,

    // Files and Directories
    pyproject_toml: String,
    uv_lock: String,
    requirements_txt: String,
    site_customize: String,
    velo_loader: String,
    velo_cache_dir: String,
    velo_profile_json: String,

    // Timeouts
    socket_startup_timeout: u64,
    worker_handshake_timeout: u64,
    graceful_shutdown_timeout: u64,
    default_slow_threshold_ms: u64,
    strict_optimizations: bool,
    sandbox_network_isolation: bool,
    sandbox_privilege_escalation_block: bool,

    // Network
    default_host: String,
    default_port: u16,

    // Security Matrix
    security_base_trusted_prefixes: String,
    security_base_env_whitelist: String,
    security_macos_base_trusted_prefixes: String,
    security_macos_base_env_whitelist: String,
    security_linux_base_trusted_prefixes: String,
    security_linux_base_env_whitelist: String,
    security_macos_dev_trusted_prefixes: String,
    security_macos_dev_env_whitelist: String,
    security_linux_dev_trusted_prefixes: String,
    security_linux_dev_env_whitelist: String,
    security_macos_ci_trusted_prefixes: String,
    security_macos_ci_env_whitelist: String,
    security_linux_ci_trusted_prefixes: String,
    security_linux_ci_env_whitelist: String,
    security_macos_prod_trusted_prefixes: String,
    security_macos_prod_env_whitelist: String,
    security_linux_prod_trusted_prefixes: String,
    security_linux_prod_env_whitelist: String,
    security_hpc_threads: usize,
    default_blocked_paths: Vec<String>,

    // Paths Matrix
    path_socket_dir_name: String,
    path_log_dir_relative: String,
    path_cache_dir_name: String,
    path_macos_base_socket_parent: String,
    path_macos_base_log_parent: String,
    path_macos_base_xdg_fallback: String,
    path_linux_base_socket_parent: String,
    path_linux_base_log_parent: String,
    path_linux_base_xdg_fallback: String,
    path_linux_fd_dir: String,
    path_macos_fd_dir: String,
    path_macos_ci_socket_parent: String,
    path_linux_ci_socket_parent: String,

    // Python Environment SSOT (Phase 7.3+)
    python_environment: PythonEnvironment,

    // Native Preloading SSOT (Phase 6 Hardening)
    native_preload: NativePreload,
}

#[allow(dead_code)]
#[derive(Deserialize, Clone)]
struct PythonEnvironment {
    required_version: String,
    venv_path: String,
    lib_dir_pattern: String,
    lib_dynload_subdir: String,
    env_vars: Vec<String>,
}

/// Native Preloading SSOT Configuration
#[allow(dead_code)]
#[derive(Deserialize, Clone)]
struct NativePreload {
    runtime_prefix: String,
    lock_env: String,
    exe_path_env: String,
    strict_env: String,
    stage_pre_init: String,
    stage_post_init: String,
}

fn main() {
    // 0. VeloSentinel: Mandatory Environment Enforcement (One for All)
    enforce_environment_ssot();

    // 1. Re-run if config changes
    println!("cargo:rerun-if-changed=../../config/constants.toml");
    println!("cargo:rerun-if-changed=../../scripts/sync-constants.py");
    println!("cargo:rerun-if-changed=../../assets/");

    // SSOT: Force recompilation when Python interpreter changes
    // This is the FIRST-PRINCIPLES fix for the cache invalidation problem.
    // When PYO3_PYTHON changes, cargo MUST rerun build.rs and recompile PyO3.
    println!("cargo:rerun-if-env-changed=PYO3_PYTHON");
    println!("cargo:rerun-if-env-changed=UV_PYTHON");

    // RFC-0018: UV Embedding (only when feature enabled)
    #[cfg(feature = "embedded_uv")]
    {
        embed_uv_binary();
    }

    // 1b. Capture Git Hash
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output();
    let mut git_hash = match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    };

    // Check for uncommitted changes
    let is_dirty = Command::new("git")
        .args(["status", "--porcelain"])
        .output()
        .map(|o| !o.stdout.is_empty())
        .unwrap_or(false);

    if is_dirty {
        git_hash.push_str("-dirty");
    }

    // 2. Read and Parse TOML (Strict SSoT)
    let config_path = Path::new("../../config/constants.toml");
    let content = fs::read_to_string(config_path).expect("Failed to read config/constants.toml");
    let constants: Constants =
        toml::from_str(&content).expect("Failed to parse config/constants.toml - Schema Mismatch!");

    // 4. Generate Rust Constants (including Python Environment SSOT)
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("constants.rs");

    let py_env = &constants.python_environment;
    let rust_code = format!(
        "// Auto-generated by build.rs. DO NOT EDIT.\n\
         pub const PROTOCOL_VERSION: u8 = {protocol_version};\n\
         pub const SOCKET_PATH_LIMIT: usize = {socket_path_limit};\n\
         pub const MAX_MESSAGE_SIZE: usize = {max_message_size};\n\
         pub const SOCKET_STARTUP_TIMEOUT: u64 = {socket_startup_timeout};\n\
         pub const GRACEFUL_SHUTDOWN_TIMEOUT: u64 = {graceful_shutdown_timeout};\n\
         pub const DEFAULT_PORT: u16 = {default_port};\n\
         pub const BUILD_SCM_HASH: &str = \"{git_hash}\";\n\
         pub const BUILD_TARGET: &str = \"{target}\";\n\
         pub const BUILD_TARGET_ARCH: &str = \"{target_arch}\";\n\
         pub const PYTHON_VERSION: &str = \"{python_version}\";\n\
         pub const SANDBOX_NETWORK_ISOLATION: bool = {sandbox_network_isolation};\n\
         pub const SANDBOX_PRIVILEGE_ESCALATION_BLOCK: bool = {sandbox_privilege_escalation_block};\n\
         \n\
         // Python Environment SSOT (Phase 7.3+)\n\
         pub const PYTHON_REQUIRED_VERSION: &str = \"{py_required_version}\";\n\
         pub const PYTHON_VENV_PATH: &str = \"{py_venv_path}\";\n\
         pub const PYTHON_LIB_DIR_PATTERN: &str = \"{py_lib_dir_pattern}\";\n\
         pub const PYTHON_LIB_DYNLOAD_SUBDIR: &str = \"{py_lib_dynload_subdir}\";\n\
         pub const PYTHON_ENV_VARS: &[&str] = &[{py_env_vars}];\n\
         pub const PYPROJECT_TOML: &str = \"{pyproject_toml}\";\n",
        protocol_version = constants.protocol_version,
        socket_path_limit = constants.socket_path_limit,
        max_message_size = constants.max_message_size,
        socket_startup_timeout = constants.socket_startup_timeout,
        graceful_shutdown_timeout = constants.graceful_shutdown_timeout,
        default_port = constants.default_port,
        git_hash = git_hash,
        target = env::var("TARGET").unwrap_or_else(|_| "unknown".into()),
        target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "unknown".into()),
        python_version = constants.python_version,
        sandbox_network_isolation = constants.sandbox_network_isolation,
        sandbox_privilege_escalation_block = constants.sandbox_privilege_escalation_block,
        py_required_version = py_env.required_version,
        py_venv_path = py_env.venv_path,
        py_lib_dir_pattern = py_env.lib_dir_pattern,
        py_lib_dynload_subdir = py_env.lib_dynload_subdir,
        py_env_vars = py_env
            .env_vars
            .iter()
            .map(|s| format!("\"{}\"", s))
            .collect::<Vec<_>>()
            .join(", "),
        pyproject_toml = constants.pyproject_toml,
    );
    let mut final_rust_code = rust_code;

    // Add native_preload constants
    let np = &constants.native_preload;
    final_rust_code.push_str(&format!(
        "\n// Native Preloading SSOT (Phase 6 Hardening)\n\
         pub const NATIVE_PRELOAD_RUNTIME_PREFIX: &str = \"{prefix}\";\n\
         pub const NATIVE_PRELOAD_LOCK_ENV: &str = \"{lock_env}\";\n\
         pub const NATIVE_PRELOAD_EXE_PATH_ENV: &str = \"{exe_path_env}\";\n\
         pub const NATIVE_PRELOAD_STRICT_ENV: &str = \"{strict_env}\";\n\
         pub const NATIVE_PRELOAD_STAGE_PRE_INIT: &str = \"{stage_pre_init}\";\n\
         pub const NATIVE_PRELOAD_STAGE_POST_INIT: &str = \"{stage_post_init}\";\n",
        prefix = np.runtime_prefix,
        lock_env = np.lock_env,
        exe_path_env = np.exe_path_env,
        strict_env = np.strict_env,
        stage_pre_init = np.stage_pre_init,
        stage_post_init = np.stage_post_init,
    ));

    fs::write(&dest_path, final_rust_code).unwrap();

    // 5. Generate Python Constants (Declarative Sovereignty - Phase 11.0)
    generate_python_constants(&constants, &git_hash);
}

/// Generate velo_zygote/constants.py via sync-constants.py (SSOT - Phase 11.0 Fix)
///
/// DESIGN: sync-constants.py is the single source of truth for Python constants generation.
/// build.rs delegates to it instead of duplicating the generation logic.
/// This ensures pre-commit sync checks always pass.
fn generate_python_constants(_config: &Constants, _git_hash: &str) {
    // Call the Python script which is the canonical generator
    // SSOT: Use PYO3_PYTHON if set (Docker CI sets this to venv python), else fallback to python3
    let python = env::var("PYO3_PYTHON").unwrap_or_else(|_| "python3".to_string());
    let status = Command::new(&python)
        .args(["../../scripts/sync-constants.py"])
        .status();

    match status {
        Ok(s) if s.success() => {
            println!(
                "cargo:warning=✅ Generated python/velo_zygote/constants.py via sync-constants.py"
            );
        }
        Ok(s) => {
            panic!(
                "\n\n[SSOT FATAL] sync-constants.py failed with code {:?}.\n\
                 This prevents Rust and Python constants from remaining in sync.\n\
                 Fix the TOML or the script before proceeding.\n\n",
                s.code()
            );
        }
        Err(e) => {
            panic!(
                "\n\n[SSOT FATAL] Could not run sync-constants.py: {}.\n\
                 Ensure 'python3' is available and in your PATH.\n\n",
                e
            );
        }
    }
}

/// RFC-0018: Download and prepare uv binary for embedding
/// Now reads from ../../config/embedded_assets.toml for declarative platform configuration
#[cfg(feature = "embedded_uv")]
fn embed_uv_binary() {
    use std::io::{Read, Write};

    // Trigger rebuild when config changes
    println!("cargo:rerun-if-changed=../../config/embedded_assets.toml");

    // Read embedded assets config
    let config_path = Path::new("../../config/embedded_assets.toml");
    if !config_path.exists() {
        println!(
            "cargo:warning=../../config/embedded_assets.toml not found, skipping uv embedding"
        );
        return;
    }

    let config_str = fs::read_to_string(config_path).expect("Failed to read embedded_assets.toml");
    let config: toml::Value = config_str
        .parse()
        .expect("Failed to parse embedded_assets.toml");

    // Extract uv configuration
    let uv_config = config.get("uv").expect("Missing [uv] section in config");
    let version = uv_config
        .get("version")
        .and_then(|v| v.as_str())
        .expect("Missing uv.version");
    let base_url = uv_config
        .get("base_url")
        .and_then(|v| v.as_str())
        .expect("Missing uv.base_url");
    let _cache_dir = uv_config
        .get("cache_dir")
        .and_then(|v| v.as_str())
        .unwrap_or("assets");

    // Find platform-specific configuration
    let platforms = uv_config
        .get("platforms")
        .and_then(|v| v.as_array())
        .expect("Missing uv.platforms array");

    let current_os = std::env::consts::OS;
    let current_arch = std::env::consts::ARCH;

    let platform_config = platforms.iter().find(|p| {
        p.get("os").and_then(|v| v.as_str()) == Some(current_os)
            && p.get("arch").and_then(|v| v.as_str()) == Some(current_arch)
    });

    let platform = match platform_config {
        Some(p) => p,
        None => {
            println!(
                "cargo:warning=No uv platform config for {}-{}, skipping embedding",
                current_os, current_arch
            );
            return;
        }
    };

    let asset_name = platform
        .get("asset_name")
        .and_then(|v| v.as_str())
        .expect("Missing asset_name in platform config");
    let archive = platform
        .get("archive")
        .and_then(|v| v.as_str())
        .expect("Missing archive in platform config");

    let url = format!("{}/{}/{}", base_url, version, archive);
    println!(
        "cargo:warning=Loading uv config: version={}, platform={}",
        version, asset_name
    );

    let assets_dir = Path::new("../../assets");
    // Store final binary as asset_name (uv-platform), but extracted dir has same name
    // So we rename to "uv.{platform}" to avoid conflict
    let final_binary_name = format!("uv.{}", asset_name.replace("uv-", ""));
    let asset_path = assets_dir.join(&final_binary_name);
    let hash_path = assets_dir.join(format!("{}.blake3", final_binary_name));

    // Create assets directory
    fs::create_dir_all(assets_dir).expect("Failed to create assets directory");

    // Skip download if asset already exists and hash is present
    if asset_path.exists() && hash_path.exists() {
        println!(
            "cargo:warning=Using cached uv binary: {}",
            asset_path.display()
        );

        // Still need to generate uv_hash.rs from cached hash
        let cached_hash = fs::read_to_string(&hash_path).expect("Failed to read cached hash");
        let out_dir = env::var("OUT_DIR").unwrap();
        let uv_hash_path = Path::new(&out_dir).join("uv_hash.rs");
        let hash_code = format!(
            "// Auto-generated by build.rs for uv {}\npub const UV_BLAKE3_HASH: &str = \"{}\";\npub const UV_VERSION: &str = \"{}\";\n",
            version,
            cached_hash.trim(),
            version
        );
        fs::write(&uv_hash_path, hash_code).expect("Failed to write uv_hash.rs");
        return;
    }

    println!(
        "cargo:warning=Downloading uv {} for {}...",
        version, asset_name
    );

    // Download using curl (available on macOS/Linux)
    let tar_gz_path = assets_dir.join(format!("{}.tar.gz", asset_name));
    let status = Command::new("curl")
        .args(["-L", "-o", tar_gz_path.to_str().unwrap(), &url])
        .status()
        .expect("Failed to execute curl");

    if !status.success() {
        panic!("Failed to download uv binary from {}", url);
    }

    // Extract the binary
    let status = Command::new("tar")
        .args([
            "-xzf",
            tar_gz_path.to_str().unwrap(),
            "-C",
            assets_dir.to_str().unwrap(),
        ])
        .status()
        .expect("Failed to execute tar");

    if !status.success() {
        panic!("Failed to extract uv binary");
    }

    // Find the extracted uv binary (it's in a subdirectory with same name)
    let extracted_dir = assets_dir.join(asset_name);
    let extracted_binary = extracted_dir.join("uv");

    // Move uv binary to assets root (asset_name without extension)
    if extracted_binary.exists() && extracted_binary.is_file() {
        fs::copy(&extracted_binary, &asset_path).expect("Failed to copy uv binary");
        // Set executable permissions
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&asset_path, fs::Permissions::from_mode(0o755))
                .expect("Failed to set permissions");
        }
        // Cleanup extracted directory
        let _ = fs::remove_dir_all(&extracted_dir);
    } else {
        panic!(
            "uv binary not found at expected path: {}",
            extracted_binary.display()
        );
    }

    // Cleanup tar.gz
    let _ = fs::remove_file(&tar_gz_path);

    // Compute BLAKE3 hash
    let mut file = fs::File::open(&asset_path).expect("Failed to open uv binary");
    let mut contents = Vec::new();
    file.read_to_end(&mut contents)
        .expect("Failed to read uv binary");

    let hash = blake3::hash(&contents);
    let hash_hex = hash.to_hex().to_string();

    // Write hash to file
    let mut hash_file = fs::File::create(&hash_path).expect("Failed to create hash file");
    hash_file
        .write_all(hash_hex.as_bytes())
        .expect("Failed to write hash");

    // Generate Rust constant for the hash
    let out_dir = env::var("OUT_DIR").unwrap();
    let uv_hash_path = Path::new(&out_dir).join("uv_hash.rs");
    let hash_code = format!(
        "// Auto-generated by build.rs for uv {}\npub const UV_BLAKE3_HASH: &str = \"{}\";
pub const UV_VERSION: &str = \"{}\";
",
        version, hash_hex, version
    );
    fs::write(&uv_hash_path, hash_code).expect("Failed to write uv_hash.rs");

    println!(
        "cargo:warning=uv {} embedded, BLAKE3: {}...{}",
        version,
        &hash_hex[..8],
        &hash_hex[hash_hex.len() - 8..]
    );
}

/// One for All: Mandatory environment enforcement based on Cargo.toml metadata
fn enforce_environment_ssot() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    // SSOT: Read directly from config/constants.toml
    let config_path = Path::new("../../config/constants.toml");
    let content = fs::read_to_string(config_path).expect("Failed to read config/constants.toml");
    let constants: Constants =
        toml::from_str(&content).expect("Failed to parse config/constants.toml");

    let expected_python = constants.python_version;

    // CI-Specific Enforcements
    let is_ci = env::var("GITHUB_ACTIONS").is_ok();
    if is_ci {
        // 1. Mandatory PYO3_PYTHON
        if env::var("PYO3_PYTHON").is_err() {
            panic!(
                "\n\n[SENTINEL FATAL] PYO3_PYTHON is NOT set in CI environment.\n\
                   Velo requires explicit interpreter paths for SSoT stability.\n\
                   Fix: Set PYO3_PYTHON in your workflow.\n\n"
            );
        }
    }

    // 2. Python Version Consistency
    // SSOT: Auto-detect project's uv Python environment before falling back to system python
    // Priority:
    // 1. PYO3_PYTHON env var (explicit override)
    // 2. .venv/bin/python (uv-managed project venv)
    // 3. python3 (system fallback - NOT RECOMMENDED)
    let python_path = env::var("PYO3_PYTHON").unwrap_or_else(|_| {
        // SSOT: Try uv python find first
        let uv_find_out = Command::new("uv").args(["python", "find"]).output();

        if let Ok(o) = uv_find_out
            && o.status.success()
        {
            let path = String::from_utf8_lossy(&o.stdout).trim().to_string();
            println!("cargo:warning=[SSOT] Auto-detected uv Python: {}", path);
            println!("cargo:rustc-env=PYO3_PYTHON={}", path);
            return path;
        }

        // Fallback to uv-managed .venv path
        let venv_python = Path::new(".venv/bin/python");
        if venv_python.exists() {
            let canonical = venv_python
                .canonicalize()
                .unwrap_or_else(|_| venv_python.to_path_buf());
            println!(
                "cargo:warning=[SSOT] Auto-detected .venv Python: {}",
                canonical.display()
            );
            // CRITICAL: Tell PyO3 to use this Python for compilation
            println!("cargo:rustc-env=PYO3_PYTHON={}", canonical.display());
            return canonical.to_string_lossy().to_string();
        }

        // Fallback to system python with warning
        println!(
            "cargo:warning=[SSOT] WARNING: No uv or .venv found, using system python3. \
             This may cause runtime issues with different Python installations."
        );
        "python3".to_string()
    });
    let py_version_out = Command::new(&python_path)
        .arg("-c")
        .arg("import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        .output();

    match py_version_out {
        Ok(output) if output.status.success() => {
            let actual_version = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if actual_version != expected_python {
                // We only warn locally but fail in CI to enforce standard
                let msg = format!(
                    "\n\n[SENTINEL ERROR] Python version mismatch!\n\
                                  Expected: {}\n\
                                  Actual  : {} (via {})\n\n",
                    expected_python, actual_version, python_path
                );
                if is_ci {
                    panic!("{}", msg);
                } else {
                    println!("cargo:warning={}", msg);
                }
            }
        }
        _ => {
            if is_ci {
                panic!(
                    "\n\n[SENTINEL FATAL] Failed to execute Python interpreter at: {}\n\n",
                    python_path
                );
            } else {
                println!(
                    "cargo:warning=[SENTINEL] Could not verify Python version at {}",
                    python_path
                );
            }
        }
    }
}
