[meta]
category = "cli"
description = "Black: The Uncompromising Code Formatter"

[test]
entry_point = "hello.py"
# args = ["--version"]  <-- Removed, handled in wrapper due to Velo limitation
expected_output = "black, .*\\d+\\.\\d+\\.\\d+.*"
timeout = 30
