//! Embedded asset management for uv toolchain
//!
//! This module handles platform-specific binary embedding and metadata.
//! The actual binaries are downloaded at build time via build.rs.

use crate::custody::error::{CustodyError, Result};

/// Platform identifier for the current compilation target
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    MacOsArm64,
    MacOsX86_64,
    LinuxX86_64,
    LinuxArm64,
}

impl Platform {
    /// Detect the current platform at compile time
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    pub const CURRENT: Platform = Platform::MacOsArm64;

    #[cfg(all(target_os = "macos", target_arch = "x86_64"))]
    pub const CURRENT: Platform = Platform::MacOsX86_64;

    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    pub const CURRENT: Platform = Platform::LinuxX86_64;

    #[cfg(all(target_os = "linux", target_arch = "aarch64"))]
    pub const CURRENT: Platform = Platform::LinuxArm64;

    // Fallback for unsupported platforms (Windows, etc.)
    #[cfg(not(any(
        all(target_os = "macos", target_arch = "aarch64"),
        all(target_os = "macos", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "aarch64")
    )))]
    pub const CURRENT: Platform = Platform::LinuxX86_64; // Will fail at runtime

    /// Get the asset filename for this platform
    pub fn asset_name(&self) -> &'static str {
        match self {
            Platform::MacOsArm64 => "uv-aarch64-apple-darwin",
            Platform::MacOsX86_64 => "uv-x86_64-apple-darwin",
            Platform::LinuxX86_64 => "uv-x86_64-unknown-linux-musl",
            Platform::LinuxArm64 => "uv-aarch64-unknown-linux-musl",
        }
    }
}

// =============================================================================
// Embedded Binary Assets (RFC-0018 Phase 5)
// =============================================================================

/// Include the uv binary using build.rs generated path
/// The binary is downloaded by build.rs and stored in assets/
#[cfg(all(feature = "embedded_uv", target_os = "macos", target_arch = "aarch64"))]
static UV_BYTES: &[u8] = include_bytes!("../../assets/uv.aarch64-apple-darwin");

#[cfg(all(feature = "embedded_uv", target_os = "macos", target_arch = "x86_64"))]
static UV_BYTES: &[u8] = include_bytes!("../../assets/uv.x86_64-apple-darwin");

#[cfg(all(feature = "embedded_uv", target_os = "linux", target_arch = "x86_64"))]
static UV_BYTES: &[u8] = include_bytes!("../../assets/uv.x86_64-unknown-linux-musl");

#[cfg(all(feature = "embedded_uv", target_os = "linux", target_arch = "aarch64"))]
static UV_BYTES: &[u8] = include_bytes!("../../assets/uv.aarch64-unknown-linux-musl");

// Fallback: no embedded bytes when feature disabled or unsupported platform
#[cfg(not(all(
    feature = "embedded_uv",
    any(
        all(target_os = "macos", target_arch = "aarch64"),
        all(target_os = "macos", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "aarch64")
    )
)))]
static UV_BYTES: &[u8] = &[];

// Include the BLAKE3 hash generated by build.rs
#[cfg(feature = "embedded_uv")]
include!(concat!(env!("OUT_DIR"), "/uv_hash.rs"));

#[cfg(not(feature = "embedded_uv"))]
mod uv_hash_fallback {
    pub const UV_BLAKE3_HASH: &str = "";
    pub const UV_VERSION: &str = "";
}
#[cfg(not(feature = "embedded_uv"))]
use uv_hash_fallback::*;

/// Embedded uv binary asset
pub struct UvAsset {
    /// Platform this asset is for
    pub platform: Platform,
}

impl UvAsset {
    /// Check if embedded assets are available
    pub fn is_available() -> bool {
        cfg!(feature = "embedded_uv") && !UV_BYTES.is_empty()
    }

    /// Get the embedded asset for the current platform
    pub fn current() -> Result<Self> {
        // Check if we're on a supported platform
        #[cfg(not(any(
            all(target_os = "macos", target_arch = "aarch64"),
            all(target_os = "macos", target_arch = "x86_64"),
            all(target_os = "linux", target_arch = "x86_64"),
            all(target_os = "linux", target_arch = "aarch64")
        )))]
        {
            return Err(CustodyError::UnsupportedPlatform);
        }

        if !Self::is_available() {
            return Err(CustodyError::UnsupportedPlatform);
        }

        Ok(Self {
            platform: Platform::CURRENT,
        })
    }

    /// Get the raw bytes of the embedded binary
    pub fn bytes(&self) -> Result<&'static [u8]> {
        if UV_BYTES.is_empty() {
            return Err(CustodyError::UnsupportedPlatform);
        }
        Ok(UV_BYTES)
    }

    /// Get the expected BLAKE3 hash
    pub fn expected_hash(&self) -> &'static str {
        #[cfg(feature = "embedded_uv")]
        {
            UV_BLAKE3_HASH
        }
        #[cfg(not(feature = "embedded_uv"))]
        {
            ""
        }
    }

    /// Get the embedded UV version
    pub fn version(&self) -> &'static str {
        #[cfg(feature = "embedded_uv")]
        {
            UV_VERSION
        }
        #[cfg(not(feature = "embedded_uv"))]
        {
            ""
        }
    }

    /// Get the size of the embedded binary
    pub fn size(&self) -> usize {
        UV_BYTES.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_platform_asset_name() {
        assert_eq!(Platform::MacOsArm64.asset_name(), "uv-aarch64-apple-darwin");
        assert_eq!(Platform::MacOsX86_64.asset_name(), "uv-x86_64-apple-darwin");
        assert_eq!(
            Platform::LinuxX86_64.asset_name(),
            "uv-x86_64-unknown-linux-musl"
        );
        assert_eq!(
            Platform::LinuxArm64.asset_name(),
            "uv-aarch64-unknown-linux-musl"
        );
    }

    #[test]
    fn test_current_platform_detection() {
        // Should compile and not panic
        let _ = Platform::CURRENT;
    }
}
