//! Zygote auto-configuration
//!
//! Parses profile data from `velo run --profile` to generate
//! preload configuration for Zygote.

use crate::profile::ProfileData;
use anyhow::Result;
use std::path::Path;

/// Default threshold for including a module in preload (in seconds)
const PRELOAD_THRESHOLD_SECS: f64 = 0.05; // 50ms

/// Maximum number of modules to preload
const MAX_PRELOAD_MODULES: usize = 10;

/// Auto-configuration result
#[derive(Debug, Clone)]
pub struct ZygoteConfig {
    /// Modules to preload
    pub preload: Vec<String>,
    /// Estimated startup savings (in seconds)
    pub estimated_savings_secs: f64,
}

impl ZygoteConfig {
    /// Generate config from profile data file
    pub fn from_profile_file(path: &Path) -> Result<Self> {
        let profile = ProfileData::from_file(path)?;
        Ok(Self::from_profile(&profile))
    }

    /// Generate config from profile data
    pub fn from_profile(profile: &ProfileData) -> Self {
        let top = profile.top_imports(MAX_PRELOAD_MODULES);

        let mut preload = Vec::new();
        let mut estimated_savings_secs = 0.0;

        for (name, time_secs) in top {
            if time_secs >= PRELOAD_THRESHOLD_SECS {
                // Only include top-level modules (not submodules)
                let top_module = name.split('.').next().unwrap_or(name);

                // Avoid duplicates
                if !preload.contains(&top_module.to_string()) {
                    preload.push(top_module.to_string());
                    estimated_savings_secs += time_secs;
                }
            }
        }

        Self {
            preload,
            estimated_savings_secs,
        }
    }

    /// Format as TOML for velo.toml
    pub fn to_toml(&self) -> String {
        let mut output = String::new();
        output.push_str("# Velo Zygote Configuration\n");
        output.push_str("# Generated by: velo zygote auto-config\n\n");
        output.push_str("[zygote]\n");
        output.push_str("enabled = true\n");

        if self.preload.is_empty() {
            output.push_str("preload = []\n");
        } else {
            output.push_str("preload = [\n");
            for module in &self.preload {
                output.push_str(&format!("    \"{}\",\n", module));
            }
            output.push_str("]\n");
        }

        output.push_str(&format!(
            "\n# Estimated startup savings: {:.0}ms\n",
            self.estimated_savings_secs * 1000.0
        ));

        output
    }

    /// Format as human-readable summary
    pub fn summary(&self) -> String {
        let mut output = String::new();
        output.push_str("📊 Auto-Configuration Results\n");
        output.push_str("════════════════════════════════════════\n\n");

        if self.preload.is_empty() {
            output.push_str("No modules found exceeding 50ms threshold.\n");
            output.push_str("Consider running with heavier imports.\n");
        } else {
            output.push_str(&format!("Preload modules ({}):\n", self.preload.len()));
            for module in &self.preload {
                output.push_str(&format!("  • {}\n", module));
            }
            output.push_str(&format!(
                "\nEstimated startup savings: {:.0}ms\n",
                self.estimated_savings_secs * 1000.0
            ));
        }

        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_to_toml() {
        let config = ZygoteConfig {
            preload: vec!["numpy".to_string(), "pandas".to_string()],
            estimated_savings_secs: 0.5,
        };

        let toml = config.to_toml();
        assert!(toml.contains("preload = ["));
        assert!(toml.contains("\"numpy\""));
        assert!(toml.contains("\"pandas\""));
        assert!(toml.contains("500ms"));
    }

    #[test]
    fn test_empty_config() {
        let config = ZygoteConfig {
            preload: vec![],
            estimated_savings_secs: 0.0,
        };

        let toml = config.to_toml();
        assert!(toml.contains("preload = []"));
    }
}
