//! Centralized path logic for Velo (RFC-0012)
//!
//! Provides canonical resolution for:
//! - Socket directory (XDG_RUNTIME_DIR -> TMPDIR)
//! - Socket file path
//! - Permission enforcement (0700)

#[cfg(target_os = "linux")]
use std::os::linux::net::SocketAddrExt;
use std::path::{Path, PathBuf};
// RFC-0012: Constants are now auto-generated by build.rs from config/constants.toml
pub use crate::common::constants::*;

pub struct VeloPaths;

// Standard Filenames (RFC-0012)
pub const PYPROJECT_TOML: &str = "pyproject.toml";
pub const UV_LOCK: &str = "uv.lock";
pub const REQUIREMENTS_TXT: &str = "requirements.txt";
pub use std::sync::atomic::{AtomicU64, Ordering};
pub const SITE_CUSTOMIZE: &str = "sitecustomize.py";
pub const VELO_LOADER: &str = "velo_loader.py";
pub const VELO_CACHE_DIR: &str = ".velo/cache";
pub const VELO_PROFILE_JSON: &str = "velo_profile.json";

/// Global sequence for worker sockets to ensure uniqueness across respawns.
static SOCKET_COUNTER: AtomicU64 = AtomicU64::new(0);

impl VeloPaths {
    /// Get the canonical socket directory using hierarchical path resolution.
    pub fn socket_dir() -> PathBuf {
        let uid = unsafe { libc::getuid() };

        // RFC-0012 Phase 6.5: Config-driven path resolution
        // Check for environment override first
        if let Some(socket_override) = std::env::var("VELO_SOCKET_DIR")
            .ok()
            .filter(|s| !s.is_empty())
        {
            // DEF-72-P01: Always enforce 0700 permissions even on override paths
            let path = PathBuf::from(&socket_override);
            ensure_socket_dir(&path);
            return path;
        }

        // Determine OS and environment
        let os_name = match std::env::consts::OS {
            "macos" => "macos",
            _ => "linux",
        };
        let env_mode = std::env::var("VELO_ENV").unwrap_or_else(|_| "dev".to_string());

        // Try environment-specific override first (e.g., path_macos_ci_socket_parent)
        let env_key = format!("path_{}_{}_socket_parent", os_name, env_mode);
        let base_key = format!("path_{}_base_socket_parent", os_name);

        let parent_path = Self::get_path_config(&env_key)
            .or_else(|| Self::get_path_config(&base_key))
            .unwrap_or_else(|| "/tmp".to_string());

        // Expand placeholders
        let expanded_parent = Self::expand_path_placeholders(&parent_path);
        let dir_name = format!("velo-{}", uid);

        let socket_path = PathBuf::from(expanded_parent).join(&dir_name);

        // Validate length constraint
        if socket_path.to_string_lossy().len() + 30 <= SOCKET_PATH_LIMIT {
            return socket_path;
        }

        // Fallback to /tmp if path is too long
        PathBuf::from("/tmp").join(dir_name)
    }

    /// Expand placeholders in path strings
    fn expand_path_placeholders(s: &str) -> String {
        let mut result = s.to_string();

        if let Ok(home) = std::env::var("HOME") {
            result = result.replace("${HOME}", &home);
        }

        if result.contains("${XDG_RUNTIME_DIR}") {
            if let Ok(xdg) = std::env::var("XDG_RUNTIME_DIR") {
                result = result.replace("${XDG_RUNTIME_DIR}", &xdg);
            } else {
                // Fallback to /tmp if XDG_RUNTIME_DIR not set
                result = result.replace("${XDG_RUNTIME_DIR}", "/tmp");
            }
        }

        if result.contains("${TMPDIR}") {
            result = result.replace("${TMPDIR}", &std::env::temp_dir().to_string_lossy());
        }

        if result.contains("${UID}") {
            let uid = unsafe { libc::getuid() };
            result = result.replace("${UID}", &uid.to_string());
        }

        result
    }

    /// Get a path config value from the embedded constants
    fn get_path_config(key: &str) -> Option<String> {
        // Delegate to the config extraction logic
        crate::config::extract_path_config(key)
    }

    /// Get the full Zygote socket path.
    pub fn zygote_socket() -> PathBuf {
        if let Some(path_str) = std::env::var("VELO_ZYGOTE_SOCKET")
            .ok()
            .filter(|p| !p.is_empty())
        {
            if path_str.len() <= SOCKET_PATH_LIMIT {
                return PathBuf::from(path_str);
            } else {
                eprintln!(
                    "⚠️ WARNING: VELO_ZYGOTE_SOCKET is too long ({} bytes, max {}). Falling back to safe default.",
                    path_str.len(),
                    SOCKET_PATH_LIMIT
                );
            }
        }

        let dir = Self::socket_dir();
        ensure_socket_dir(&dir);
        dir.join(format!("velo-zygote-v{:02x}.sock", PROTOCOL_VERSION))
    }

    /// Generate a standardized, short path for a worker socket.
    /// Uses atomic counter to prevent collisions when workers respawn.
    pub fn worker_socket(worker_id: u64) -> PathBuf {
        let dir = Self::socket_dir();
        ensure_socket_dir(&dir);

        // Monotonic counter - never repeats in same supervisor lifetime
        // Format: w-{worker_id}-{seq}.s (e.g., w-0-5.s = worker 0's 5th spawn)
        let seq = SOCKET_COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = dir.join(format!("v-worker-{}-{}.sock", worker_id, seq));
        eprintln!(
            "[PATHS] Generated worker socket: {} (id={}, seq={})",
            path.display(),
            worker_id,
            seq
        );
        path
    }

    /// Get the log path for the Zygote.
    pub fn zygote_log() -> PathBuf {
        if let Some(path_str) = std::env::var("VELO_ZYGOTE_LOG")
            .ok()
            .filter(|p| !p.is_empty())
        {
            return PathBuf::from(path_str);
        }

        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
        let log_dir = PathBuf::from(home).join(".local/state/velo");

        // Ensure log directory exists
        if !log_dir.exists() {
            let _ = std::fs::create_dir_all(&log_dir);
        }

        log_dir.join("zygote.log")
    }

    /// Get the path to the Zygote's profiling data.
    pub fn zygote_profile(project_root: &Path) -> PathBuf {
        Self::project_file(project_root, VELO_PROFILE_JSON)
    }

    /// Get a project-relative file path.
    pub fn project_file(project_root: &Path, file_name: &str) -> PathBuf {
        project_root.join(file_name)
    }

    /// Canonical path to pyproject.toml
    pub fn pyproject(project_root: &Path) -> PathBuf {
        Self::project_file(project_root, PYPROJECT_TOML)
    }

    /// Canonical path to uv.lock
    pub fn uv_lock(project_root: &Path) -> PathBuf {
        Self::project_file(project_root, UV_LOCK)
    }

    /// Canonical path to sitecustomize.py
    pub fn site_customize(dir: &Path) -> PathBuf {
        dir.join(SITE_CUSTOMIZE)
    }
}

/// Legacy wrapper for get_socket_dir (delegates to VeloPaths)
pub fn get_socket_dir() -> PathBuf {
    VeloPaths::socket_dir()
}

/// Legacy wrapper for get_socket_path (delegates to VeloPaths)
pub fn get_socket_path() -> PathBuf {
    VeloPaths::zygote_socket()
}

/// Ensure directory exists with 0700 permissions.
pub fn ensure_socket_dir(dir: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;

    if !dir.exists() {
        let old_mask = unsafe { libc::umask(0o077) };
        let res = std::fs::create_dir_all(dir);
        unsafe { libc::umask(old_mask) };
        if res.is_err() {
            return false;
        }
    }

    // Force 0700
    if let Ok(metadata) = dir.metadata() {
        let mut perms = metadata.permissions();
        perms.set_mode(0o700);
        if std::fs::set_permissions(dir, perms).is_err() {
            return false;
        }
    }

    // Verify
    if let Ok(metadata) = dir.metadata() {
        let mode = metadata.permissions().mode() & 0o777;
        if mode != 0o700 {
            eprintln!(
                "⚠️ SECURITY: Socket dir has insecure permissions: {:o}",
                mode
            );
        }
    }

    true
}

/// Legacy wrapper for generate_worker_socket_path (delegates to VeloPaths)
pub fn generate_worker_socket_path(worker_id: u64) -> PathBuf {
    VeloPaths::worker_socket(worker_id)
}

// =============================================================================
// Gate G: Abstract Namespace Sockets (RFC-0019 SEC-07-001)
// =============================================================================

/// Check if abstract namespace sockets are supported (Linux only).
/// Abstract sockets eliminate TOCTOU race conditions by avoiding filesystem.
#[inline]
pub fn is_abstract_socket_supported() -> bool {
    cfg!(target_os = "linux")
}

/// Generate an abstract socket name for a worker (Linux only).
/// Format: `\0velo-{uid}-w-{worker_id}-{seq}`
///
/// On non-Linux systems, returns None (use filesystem paths instead).
#[cfg(target_os = "linux")]
pub fn worker_abstract_socket_name(worker_id: u64) -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static ABSTRACT_COUNTER: AtomicU64 = AtomicU64::new(0);

    let uid = unsafe { libc::getuid() };
    let seq = ABSTRACT_COUNTER.fetch_add(1, Ordering::Relaxed);

    // Note: The actual \0 prefix is added when creating SocketAddr
    format!("velo-{}-w-{}-{}", uid, worker_id, seq)
}

/// Generate an abstract socket name for the Zygote (Linux only).
/// Format: `\0velo-{uid}-zygote-v{version}`
#[cfg(target_os = "linux")]
pub fn zygote_abstract_socket_name() -> String {
    let uid = unsafe { libc::getuid() };
    format!("velo-{}-zygote-v{:02x}", uid, PROTOCOL_VERSION)
}

/// Create a SocketAddr for abstract namespace socket (Linux).
#[cfg(target_os = "linux")]
pub fn abstract_socket_addr(name: &str) -> std::io::Result<std::os::unix::net::SocketAddr> {
    std::os::unix::net::SocketAddr::from_abstract_name(name.as_bytes())
}

/// Bind to an abstract namespace socket (Linux).
#[cfg(target_os = "linux")]
pub fn bind_abstract_socket(name: &str) -> std::io::Result<std::os::unix::net::UnixListener> {
    use std::os::unix::net::UnixListener;
    let addr = abstract_socket_addr(name)?;
    UnixListener::bind_addr(&addr)
}
#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_expand_path_placeholders() {
        unsafe {
            std::env::set_var("HOME", "/mock/home");
            assert_eq!(
                VeloPaths::expand_path_placeholders("${HOME}/test"),
                "/mock/home/test"
            );

            std::env::set_var("XDG_RUNTIME_DIR", "/mock/xdg");
            assert_eq!(
                VeloPaths::expand_path_placeholders("${XDG_RUNTIME_DIR}/velo"),
                "/mock/xdg/velo"
            );

            std::env::remove_var("XDG_RUNTIME_DIR");
            assert_eq!(
                VeloPaths::expand_path_placeholders("${XDG_RUNTIME_DIR}/velo"),
                "/tmp/velo"
            );
        }
    }

    #[test]
    fn test_ensure_socket_dir_permissions() {
        let dir = tempdir().unwrap();
        let socket_dir = dir.path().join("velo-test");

        // Create with Loose permissions (0777)
        fs::create_dir_all(&socket_dir).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&socket_dir, fs::Permissions::from_mode(0o777)).unwrap();
        }

        assert!(ensure_socket_dir(&socket_dir));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let metadata = fs::metadata(&socket_dir).unwrap();
            let mode = metadata.permissions().mode() & 0o777;
            // PROSECUTOR: This test SHOULD FAIL if the code doesn't strictly enforce 0700.
            assert_eq!(
                mode, 0o700,
                "SECURITY: ensure_socket_dir failed to enforce 0700 (got {:o})",
                mode
            );
        }
    }

    #[test]
    fn test_socket_path_limit_logic() {
        // Since we can't change the constant SOCKET_PATH_LIMIT easily, we test the logic behavior
        // by observing where it points.
        let uid = unsafe { libc::getuid() };
        let _dir_name = format!("velo-{}", uid);

        // Scenario 1: No override
        let sdir = VeloPaths::socket_dir();
        // If the default path is already > limit, it should have fallen back to /tmp
        if sdir.to_string_lossy().len() + 30 > SOCKET_PATH_LIMIT {
            assert!(
                sdir.to_string_lossy().starts_with("/tmp/"),
                "Should fallback to /tmp when path too long"
            );
        }

        // Scenario 2: Forced override
        unsafe {
            let too_long = "a".repeat(200);
            std::env::set_var("VELO_SOCKET_DIR", &too_long);
            // VeloPaths handles VELO_SOCKET_DIR by returning it directly (currently no length check on override!)
            // PROSECUTOR: This is a potential bug if the override is also too long.
            assert_eq!(VeloPaths::socket_dir(), PathBuf::from(&too_long));
            std::env::remove_var("VELO_SOCKET_DIR");
        }
    }

    #[test]
    fn test_worker_socket_uniqueness() {
        let s1 = VeloPaths::worker_socket(0);
        let s2 = VeloPaths::worker_socket(0);
        assert_ne!(
            s1, s2,
            "Worker sockets must be unique across spawns to prevent TOCTOU/STALE"
        );
    }
}
