//! Centralized path logic for Velo (RFC-0012)
//!
//! Provides canonical resolution for:
//! - Socket directory (XDG_RUNTIME_DIR -> TMPDIR)
//! - Socket file path
//! - Permission enforcement (0700)

use std::path::{Path, PathBuf};
// RFC-0012: Constants are now auto-generated by build.rs from config/constants.toml
// RFC-0012: Constants are now auto-generated by build.rs from config/constants.toml
pub use crate::common::constants::*;

pub struct VeloPaths;

// Standard Filenames (RFC-0012)
pub const PYPROJECT_TOML: &str = "pyproject.toml";
pub const UV_LOCK: &str = "uv.lock";
pub const REQUIREMENTS_TXT: &str = "requirements.txt";
pub const SITE_CUSTOMIZE: &str = "sitecustomize.py";
pub const VELO_LOADER: &str = "velo_loader.py";
pub const VELO_CACHE_DIR: &str = ".velo_cache";
pub const VELO_PROFILE_JSON: &str = "velo_profile.json";

impl VeloPaths {
    /// Get the canonical socket directory.
    pub fn socket_dir() -> PathBuf {
        let uid = unsafe { libc::getuid() };
        let dir_name = format!("velo-{}", uid);

        // RFC-0012: On macOS/Unix, we MUST prioritize /tmp for sockets because
        // hermetic test environments often have extremely long HOME/TMPDIR paths
        // that exceed the 104-character AF_UNIX limit.
        let short_path = PathBuf::from("/tmp").join(&dir_name);

        // Check if short path is viable
        if short_path.to_string_lossy().len() + 30 <= SOCKET_PATH_LIMIT {
            return short_path;
        }

        // Fallback to environment variables only if necessary
        if let Ok(xdg) = std::env::var("XDG_RUNTIME_DIR") {
            return PathBuf::from(xdg).join("velo");
        }

        std::env::temp_dir().join(dir_name)
    }

    /// Get the full Zygote socket path.
    pub fn zygote_socket() -> PathBuf {
        if let Some(path_str) = std::env::var("VELO_ZYGOTE_SOCKET")
            .ok()
            .filter(|p| !p.is_empty())
        {
            if path_str.len() <= SOCKET_PATH_LIMIT {
                return PathBuf::from(path_str);
            } else {
                eprintln!(
                    "⚠️ WARNING: VELO_ZYGOTE_SOCKET is too long ({} bytes, max {}). Falling back to safe default.",
                    path_str.len(),
                    SOCKET_PATH_LIMIT
                );
            }
        }

        let dir = Self::socket_dir();
        ensure_socket_dir(&dir);
        dir.join(format!("velo-zygote-v{:02x}.sock", PROTOCOL_VERSION))
    }

    /// Generate a standardized, short path for a worker socket.
    pub fn worker_socket(worker_id: u64) -> PathBuf {
        let dir = Self::socket_dir();
        ensure_socket_dir(&dir);
        dir.join(format!("w-{}.s", worker_id))
    }

    /// Get the log path for the Zygote.
    pub fn zygote_log() -> PathBuf {
        if let Some(path_str) = std::env::var("VELO_ZYGOTE_LOG")
            .ok()
            .filter(|p| !p.is_empty())
        {
            return PathBuf::from(path_str);
        }

        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
        // Standard macOS/Linux log path location
        PathBuf::from(home)
            .join(".local/state/velo")
            .join("zygote.log")
    }

    /// Get the path to the Zygote's profiling data.
    pub fn zygote_profile(project_root: &Path) -> PathBuf {
        Self::project_file(project_root, VELO_PROFILE_JSON)
    }

    /// Get a project-relative file path.
    pub fn project_file(project_root: &Path, file_name: &str) -> PathBuf {
        project_root.join(file_name)
    }

    /// Canonical path to pyproject.toml
    pub fn pyproject(project_root: &Path) -> PathBuf {
        Self::project_file(project_root, PYPROJECT_TOML)
    }

    /// Canonical path to uv.lock
    pub fn uv_lock(project_root: &Path) -> PathBuf {
        Self::project_file(project_root, UV_LOCK)
    }

    /// Canonical path to sitecustomize.py
    pub fn site_customize(dir: &Path) -> PathBuf {
        dir.join(SITE_CUSTOMIZE)
    }
}

/// Legacy wrapper for get_socket_dir (delegates to VeloPaths)
pub fn get_socket_dir() -> PathBuf {
    VeloPaths::socket_dir()
}

/// Legacy wrapper for get_socket_path (delegates to VeloPaths)
pub fn get_socket_path() -> PathBuf {
    VeloPaths::zygote_socket()
}

/// Ensure directory exists with 0700 permissions.
pub fn ensure_socket_dir(dir: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;

    if !dir.exists() {
        let old_mask = unsafe { libc::umask(0o077) };
        let res = std::fs::create_dir_all(dir);
        unsafe { libc::umask(old_mask) };
        if res.is_err() {
            return false;
        }
    }

    // Force 0700
    if let Ok(metadata) = dir.metadata() {
        let mut perms = metadata.permissions();
        perms.set_mode(0o700);
        if std::fs::set_permissions(dir, perms).is_err() {
            return false;
        }
    }

    // Verify
    if let Ok(metadata) = dir.metadata() {
        let mode = metadata.permissions().mode() & 0o777;
        if mode != 0o700 {
            eprintln!(
                "⚠️ SECURITY: Socket dir has insecure permissions: {:o}",
                mode
            );
        }
    }

    true
}

/// Legacy wrapper for generate_worker_socket_path (delegates to VeloPaths)
pub fn generate_worker_socket_path(worker_id: u64) -> PathBuf {
    VeloPaths::worker_socket(worker_id)
}
